---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: minio
  namespace: monitoring
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
