---
apiVersion: v1
kind: Namespace
metadata:
  name: xavki

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: xavki
  namespace: xavki
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: xavki.kub
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: xavki
            port:
              number: 8080

---
kind: Service
apiVersion: v1
metadata:
  name: xavki
  namespace: xavki
  labels:
    app: xavki
spec:
  selector:
    app: xavki
  ports:
  - name: xavki
    protocol: TCP
    port: 8080
    targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xavki
  namespace: xavki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xavki
  template:
    metadata:
      labels:
        app: xavki
    spec:
      containers:
      - name: xavki
        image: priximmo/flaskexporter:v0.1
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8080

