{
 "title": "Scylla2",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(scylla_scylladb_current_version,cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 0 },
   "options": {
    "content": "<img src=https://www.scylladb.com/wp-content/uploads/brand-logo-horiz@2x.png/>"
   }
  },
  { "title": "Cluster overview - $cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(scylla_scylladb_current_version{cluster=~\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Writes",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 10, "x": 3, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(scylla_storage_proxy_coordinator_write_latency_count{scheduling_group_name=\"statement\",cluster=\"$cluster\"}[1m])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reads",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 10, "x": 13, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(scylla_storage_proxy_coordinator_read_latency_count{scheduling_group_name=\"statement\",cluster=\"$cluster\"}[1m])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unreachable",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(count(scrape_samples_scraped{cluster=~\"$cluster\"}==0) OR vector(0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reads/s",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(scylla_storage_proxy_coordinator_read_latency_count{cluster=~\"$cluster\",scheduling_group_name=\"statement\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Writes/s",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(scylla_storage_proxy_coordinator_write_latency_count{cluster=~\"$cluster\",scheduling_group_name=\"statement\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 18 } },
  {
   "type": "table",
   "gridPos": { "h": 5, "w": 23, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "count without(cpu, mode) (node_cpu_seconds_total{instance=~\"scylla.*\", mode=\"idle\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg by (dc, instance) (irate(node_cpu_seconds_total{instance=~\"scylla.*\",mode=\"iowait\"}[1m])) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(node_load1{instance=~\"scylla.*\"} / count without(cpu, mode) (node_cpu_seconds_total{instance=~\"scylla.*\", mode=\"idle\"})) by (instance, dc)",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"scylla.*\"} / 1024 / 1024/ 1024",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(node_memory_MemTotal_bytes{instance=~\"scylla.*\"} - node_memory_MemFree_bytes{instance=~\"scylla.*\"} - node_memory_Cached_bytes{instance=~\"scylla.*\"} - node_memory_Buffers_bytes{instance=~\"scylla.*\"}) by (instance, dc) / 1024 /1024 /1024",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=~\"scylla.*\", mountpoint=\"/\"} /1024/1024/1024",
     "legendFormat": "__auto"
    },
    {
     "expr": "(node_filesystem_size_bytes{instance=~\"scylla.*\", mountpoint=\"/\"} - node_filesystem_free_bytes{instance=~\"scylla.*\", mountpoint=\"/\"}) /1024/1024/1024",
     "legendFormat": "__auto"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "IOWait",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by (dc, instance) (irate(node_cpu_seconds_total{instance=~\"scylla.*\",mode=\"iowait\"}[1m])) * 100",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Load per CPU",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(node_load1{instance=~\"scylla.*\"} / count without(cpu, mode) (node_cpu_seconds_total{instance=~\"scylla.*\", mode=\"idle\"})) by (instance)",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Requests/s",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "si:" } },
   "targets": [
    {
     "expr": "sum(rate(scylla_transport_requests_served{cluster=~\"$cluster\"}[60s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connections",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 39 },
     "targets": [
      {
       "expr": "sum(scylla_transport_current_connections{cluster=~\"$cluster\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "TCP connections established",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(node_netstat_Tcp_CurrEstab{instance=~\"scylla.*\"}) by (instance)",
       "legendFormat": "TCP established socket"
      }
     ]
    }
   ]
  },
  {
   "title": "Reads & Writes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bloom Filter Memory",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 115 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(scylla_sstables_bloom_filter_memory_size{cluster=\"$cluster\"})by(instance)",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Read latencies",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 7, "y": 115 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "sum(rlatencyp99{by=\"cluster\",cluster=~\"$cluster\"})",
       "legendFormat": "P99"
      },
      {
       "expr": "rlatencyp95{by=\"cluster\", cluster=~\"$cluster\"}",
       "legendFormat": "P95"
      }
     ]
    },
    {
     "title": "Write latencies",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 13, "y": 115 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "wlatencyp99{by=\"cluster\", cluster=~\"$cluster\",scheduling_group_name=\"statement\"}",
       "legendFormat": "P99"
      },
      {
       "expr": "wlatencyp95{by=\"cluster\", cluster=~\"$cluster\",scheduling_group_name=\"statement\"}",
       "legendFormat": "P95"
      }
     ]
    },
    {
     "title": "Partitions evicted",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 5, "x": 19, "y": 115 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(scylla_cache_partition_evictions{cluster=\"$cluster\"}[1m]))by(instance)",
       "legendFormat": "{{hostname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Disks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk - iops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 116 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(node_disk_reads_completed_total{instance=~\"scylla.*\"}[1m])",
       "legendFormat": "Reads - {{ instance }}"
      },
      {
       "expr": "0-rate(node_disk_writes_completed_total{instance=~\"scylla.*\"}[1m])",
       "legendFormat": "Writes - {{ instance }}"
      }
     ]
    },
    {
     "title": "Size - /",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 116 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "(node_filesystem_size_bytes{instance=~\"scylla.*\", mountpoint=\"/\"} - node_filesystem_free_bytes{instance=~\"scylla.*\", mountpoint=\"/\"})",
       "legendFormat": "{{instance}} - {{mountpoint}}"
      }
     ]
    },
    {
     "title": "Queue Write",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 124 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(scylla_io_queue_total_write_bytes{cluster=\"$cluster\"}[1m]))by(instance)",
       "legendFormat": "{{instance}} - {{mountpoint}}"
      }
     ]
    },
    {
     "title": "Queue Read",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 124 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(scylla_io_queue_total_read_bytes{cluster=\"$cluster\"}[1m]))by(instance,mountpoint)",
       "legendFormat": "{{instance}} - {{mountpoint}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Others",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Read Memory Consumption",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(scylla_database_active_reads_memory_consumption{cluster=\"$cluster\"})by(instance)",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Cache row actions",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 6, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(scylla_cache_dummy_row_hits{cluster=\"$cluster\"}[1m]))",
       "legendFormat": "Hits"
      },
      {
       "expr": "sum(rate(scylla_cache_row_evictions{cluster=\"$cluster\"}[1m]))",
       "legendFormat": "Evictions"
      },
      {
       "expr": "sum(rate(scylla_cache_row_insertions[1m]))",
       "legendFormat": "Insertions"
      }
     ]
    },
    {
     "title": "Cache partition actions",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 15, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(scylla_cache_partition_insertions{cluster=\"$cluster\"}[1m]))",
       "legendFormat": "Insertions"
      },
      {
       "expr": "sum(rate(scylla_cache_partition_removals{cluster=\"$cluster\"}[1m]))",
       "legendFormat": "Removals"
      }
     ]
    },
    {
     "title": "Cache Hits/Misses",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(scylla_cache_row_hits{cluster=\"$cluster\"}[1m]))",
       "legendFormat": "Hit"
      },
      {
       "expr": "sum(rate(scylla_cache_row_misses{cluster=\"$cluster\"}[1m]))",
       "legendFormat": "Misses"
      }
     ]
    },
    {
     "title": "Read Timeouts",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 5, "x": 6, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "si:ops/s" } },
     "targets": [
      {
       "expr": "sum(rate(scylla_storage_proxy_coordinator_read_timeouts{cluster=\"$cluster\"}[1m]))+sum(rate(scylla_storage_proxy_coordinator_cas_read_timeouts{cluster=\"$cluster\"}[1m]))+sum(rate(scylla_storage_proxy_coordinator_range_timeouts{cluster=\"$cluster\"}[1m]))",
       "legendFormat": "Read  {{[[by]]}}"
      }
     ]
    },
    {
     "title": "Write Timeouts",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 5, "x": 11, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "si:ops/s" } },
     "targets": [
      {
       "expr": "sum(rate(scylla_storage_proxy_coordinator_write_timeouts{cluster=\"$cluster\"}[1m]))",
       "legendFormat": "Read  {{[[by]]}}"
      }
     ]
    },
    {
     "title": "Running Compactions",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 17, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(scylla_compaction_manager_compactions{cluster=\"$cluster\"})by(instance)"
      }
     ]
    }
   ]
  }
 ]
}