{
 "title": "Scylla2",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(scylla_scylladb_current_version,cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 0 },
   "options": {
    "content": "<img src=https://www.scylladb.com/wp-content/uploads/brand-logo-horiz@2x.png/>"
   }
  },
  { "title": "Cluster overview - $cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(scylla_scylladb_current_version{cluster=~\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Writes",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 10, "x": 3, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(scylla_storage_proxy_coordinator_write_latency_count{scheduling_group_name=\"statement\",cluster=\"$cluster\"}[1m])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reads",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 10, "x": 13, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(scylla_storage_proxy_coordinator_read_latency_count{scheduling_group_name=\"statement\",cluster=\"$cluster\"}[1m])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unreachable",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(count(scrape_samples_scraped{cluster=~\"$cluster\"}==0) OR vector(0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reads/s",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(scylla_storage_proxy_coordinator_read_latency_count{cluster=~\"$cluster\",scheduling_group_name=\"statement\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Writes/s",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(scylla_storage_proxy_coordinator_write_latency_count{cluster=~\"$cluster\",scheduling_group_name=\"statement\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 18 } },
  {
   "type": "table",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "count without(cpu, mode) (node_cpu_seconds_total{instance=~\"scylla.*\", mode=\"idle\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg by (dc, instance) (irate(node_cpu_seconds_total{instance=~\"scylla.*\",mode=\"iowait\"}[1m])) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(node_load1{instance=~\"scylla.*\"} / count without(cpu, mode) (node_cpu_seconds_total{instance=~\"scylla.*\", mode=\"idle\"})) by (instance, dc)",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"scylla.*\"} / 1024 / 1024/ 1024",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(node_memory_MemTotal_bytes{instance=~\"scylla.*\"} - node_memory_MemFree_bytes{instance=~\"scylla.*\"} - node_memory_Cached_bytes{instance=~\"scylla.*\"} - node_memory_Buffers_bytes{instance=~\"scylla.*\"}) by (instance, dc) / 1024 /1024 /1024",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=~\"scylla.*\", mountpoint=\"/\"} /1024/1024/1024",
     "legendFormat": "__auto"
    },
    {
     "expr": "(node_filesystem_size_bytes{instance=~\"scylla.*\", mountpoint=\"/\"} - node_filesystem_free_bytes{instance=~\"scylla.*\", mountpoint=\"/\"}) /1024/1024/1024",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}