apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: xavki2
  namespace: xavki
  labels:
    prometheus: prom2
spec:
  endpoints:
  - interval: 30s
    targetPort: 8080
    path: /metrics
    metricRelabelings:
      - sourceLabels: [__name__]
        regex: (^mycounter_client_orders_.*$)
        action: keep
  namespaceSelector:
    matchNames:
    - xavki
  selector:
    matchLabels:
      app: xavki

