#!/bin/bash
# small http wrapper for bash scripts via xinetd

ulimit -n 20480
ulimit -l 512

root='/opt/scripts'
mime='text/plain'

for script in $root/*.sh;do
  if [ -f "$script" ]; then
    $script >> /tmp/final.metrics
    sleep 0.1
  else
    exit 1
  fi
done

size=$(stat -c "%s" "/tmp/final.metrics")
printf 'HTTP/1.1 200 OK\r\nDate: %s\r\nContent-Length: %s\r\nContent-Type: %s\r\nConnection: close\r\n\r\n' "$(date)" "$size" "$mime"
cat /tmp/final.metrics
echo -en "\r\n"
rm -f /tmp/final.metrics

exit 0

