---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prometheus-operator
  namespace: monitoring
spec:
  releaseName: prometheus-operator
  chart:
    repository: https://prometheus-community.github.io/helm-charts
    name: kube-prometheus-stack
    version: 12.11.3
  values:
    prometheusOperator:
      image:
        repository: quay.io/prometheus-operator/prometheus-operator
        tag: v0.44.0
      configmapReloadImage:
        repository: quay.io/jimmidyson/configmap-reload
        tag: v0.4.0
      prometheusConfigReloaderImage:
        repository: quay.io/prometheus-operator/prometheus-config-reloader
        tag: v0.44.0
      configReloaderMemory: 32Mi
      admissionWebhooks:
        patch:
          image:
            repository: jettech/kube-webhook-certgen
            tag: v1.5.0
    nodeExporter:
      enabled: true
    prometheus:
      prometheusSpec:
        replicas: 1
        retention: 2h
        serviceMonitorSelectorNilUsesHelmValues: false
        ruleSelectorNilUsesHelmValues: false
        thanos:
          image: thanosio/thanos:v0.18.0
          objectStorageConfig:
            key: thanos.yaml
            name: thanos-objstore-config
        image:
          repository: quay.io/prometheus/prometheus
          tag: v2.22.1
        prometheusExternalLabelNameClear: true
    grafana:
      image:
        repository: grafana/grafana
        tag: 7.3.5
      adminPassword: password
      additionalDataSources:
      - name: Thanos
        url: http://thanos-query-frontend.monitoring:9090
        type: prometheus
        access: proxy
        isDefault: true
      defaultDashboardsEnabled: false
      sidecar:
        image:
          repository: kiwigrid/k8s-sidecar
          tag: 1.1.0
        datasources:
          defaultDatasourceEnabled: false
    kubeControllerManager:
      service:
        port: 10257
        targetPort: 10257
      serviceMonitor:
        https: true
        insecureSkipVerify: true
        serverName: 127.0.0.1
    kube-state-metrics:
      image:
        repository: quay.io/coreos/kube-state-metrics
        tag: v1.9.7
    kubeEtcd:
      serviceMonitor:
        scheme: https
        insecureSkipVerify: true
        caFile: /etc/prometheus/secrets/etcd-certs/ca.crt
        certFile: /etc/prometheus/secrets/etcd-certs/healthcheck-client.crt
        keyFile: /etc/prometheus/secrets/etcd-certs/healthcheck-client.key
    kubeScheduler:
      service:
        port: 10259
        targetPort: 10259
      serviceMonitor:
        https: true
        insecureSkipVerify: true
        serverName: 127.0.0.1
