---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: thanos
  namespace: monitoring
spec:
  releaseName: thanos
  helmVersion: v3
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: thanos
    version: 3.9.0
  values:
    image:
      tag: 0.18.0
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    objstoreConfig: |-
      type: "S3"
      config:
        bucket: "prometheus"
        endpoint: "minio.monitoring.svc.cluster.local:9000"
        access_key: "xavki"
        secret_key: "password"
        insecure: true
    query:
      enabled: true
      dnsDiscovery:
        enabled: true
        sidecarsService: prometheus-operated
        sidecarsNamespace: monitoring
      extraFlags:
      - --query.auto-downsampling
      replicaLabel: prometheus_replica
    queryFrontend:
      enabled: true
      config: |-
        type: IN-MEMORY
        config:
          max_size: 1GB
          max_size_items: 0
          validity: 0s
    storegateway:
      enabled: true
      persistence:
        enabled: false
    compactor:
      enabled: true
      persistence:
        enabled: false
      retentionResolutionRaw: 2d
      retentionResolution5m: 30d
      retentionResolution1h: 1y
    bucketweb:
      enabled: true

